### ISSUE TITLE
Importing the bot in paintbot-cli.js dynamically doesn't resolve path on Windows

### ISSUE THREAD

**Issue by Dr-Horv** [cygni/snakebot-client-js#13]
Stacktrace:
```
internal/process/promises.js:194
        triggerUncaughtException(err, true /* fromPromise */);
        ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:666:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at Loader.import (internal/modules/esm/loader.js:178:28)
    at importModuleDynamically (internal/modules/esm/translators.js:53:26)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:29:14)
    at Command.run (file:///C:/Users/SomeUserName\SomeDirectory\Some%20DirectoryWithSpace/paintbot-client-js/paintbot-cli.js:14:33)
    at Command.listener [as _actionHandler] (C:\Users\SomeUserName\SomeDirectory\Some DirectoryWithSpace\paintbot-client-js\node_modules\commander\index.js:408:31)
    at Command._parseCommand (C:\Users\SomeUserName\SomeDirectory\Some DirectoryWithSpace\paintbot-client-js\node_modules\commander\index.js:909:14)
    at Command.parse (C:\Users\SomeUserName\SomeDirectory\Some DirectoryWithSpace\paintbot-client-js\node_modules\commander\index.js:712:10) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**Comment by maxdavidson** [comment]
In v2 I assume?

**Comment by Dr-Horv** [comment]
Yes, sorry was supposed to post this on the Paintbot client repo. But yes, same issue in v2 here I assume since it's the same code for this part
